apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: f38zi92mr-python 
  janus-idp.io/tekton: f38zi92mr-python
  backstage.io/kubernetes-id: f38zi92mr-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: f38zi92mr-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  